/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/layout/AppBar.vue')['default']
    CaptchaCard: typeof import('./src/components/CaptchaCard.vue')['default']
    Home: typeof import('./src/components/pages/Home.vue')['default']
    Login: typeof import('./src/components/pages/Login.vue')['default']
    NotFound: typeof import('./src/components/pages/NotFound.vue')['default']
    Player: typeof import('./src/components/player/Player.vue')['default']
    Popular: typeof import('./src/components/Popular.vue')['default']
    PopularPrecious: typeof import('./src/components/PopularPrecious.vue')['default']
    PopularSeries: typeof import('./src/components/PopularSeries.vue')['default']
    Rank: typeof import('./src/components/Rank.vue')['default']
    Recommend: typeof import('./src/components/Recommend.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/pages/Search.vue')['default']
    Setting: typeof import('./src/components/pages/Setting.vue')['default']
    SideBar: typeof import('./src/components/layout/SideBar.vue')['default']
    Space: typeof import('./src/components/pages/Space.vue')['default']
    Video: typeof import('./src/components/pages/Video.vue')['default']
    VideoCard: typeof import('./src/components/VideoCard.vue')['default']
  }
}
