/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BiliIframePlayer: typeof import('./src/components/BiliIframePlayer.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search.vue')['default']
    Setting: typeof import('./src/components/Setting.vue')['default']
    Video: typeof import('./src/components/Video.vue')['default']
    VideoCard: typeof import('./src/components/VideoCard.vue')['default']
    VideoPlayer: typeof import('./src/components/VideoPlayer.vue')['default']
    VideoPlayer2: typeof import('./src/components/VideoPlayer2.vue')['default']
  }
}
